# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

inhibit_all_warnings!

target 'TimeCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for  YXFrontline
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'YYImage'
  pod 'YYWebImage'
  pod 'YYCategories'
  pod 'YYModel'
  pod 'YYCache'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'MBProgressHUD'

end


